stages:
  - test
  - mirror

test:
  stage: test
  image: babashka/babashka:latest
  before_script:
    - apt-get update && apt-get install -y ripgrep
  script:
    - bb test

mirror-github:
  stage: mirror
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git remote set-url origin "https://x-access-token:${GH_MIRROR_TOKEN}@github.com/nurazhardotcom/${CI_PROJECT_NAME}.git"
    - git push origin main --force
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  allow_failure: true
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 0
